services:
  db:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: backend_development
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    depends_on:
      - db
      - redis
    environment:
      RAILS_ENV: development
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: backend_development
      REDIS_URL: redis://redis:6379/1
      SECRET_KEY_BASE: dummykey
    volumes:
      - ./backend:/rails
    ports:
      - "3000:3000"
    command: sh -c "rm -f tmp/pids/server.pid && bin/rails db:migrate && ./bin/dev"

  frontend:
    image: node:18
    container_name: frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "5173:5173"
    environment:
      - VITE_BACKEND_URL=http://localhost:3000/
      - VITE_REDIS_URL=ws://localhost:3000/cable
    command: sh -c "npm install && npm run dev -- --host"
    depends_on:
      - backend

volumes:
  db_data:
